import {
  Controller,
  Get,
  Post,
  Put,
  Delete,
  Autowired,
  ApiQueryParams,
  reply,
  type Ctx,
} from '@forinda/kickjs'
import { TasksService } from './tasks.service'
import { createTasksSchema } from './dtos/create-tasks.dto'
import { updateTasksSchema } from './dtos/update-tasks.dto'
import { TASKS_QUERY_CONFIG } from './tasks.constants'

// Each handler annotates its `ctx` with `Ctx<KickRoutes.TasksController['<method>']>`
// so `ctx.params`, `ctx.body`, and `ctx.query` are typed end-to-end.
// The `KickRoutes` namespace is generated by `kick typegen` (auto-run on
// `kick dev`) — see https://kickjs.app/guide/typegen.
//
// Handlers RETURN their payload rather than calling `ctx.json()`: the runtime
// auto-sends it, and `kick typegen` reads the return type to fill in
// `KickRoutes[...].response` — which is what makes the typed client know what
// each route gives back. A handler that writes via `ctx.json()` and returns
// nothing infers as `unknown`. Use `reply(status, body)` (or the
// `reply.created` / `reply.noContent` sugars) when the status isn't 200, and
// `ctx.problem.*` for error branches — those send immediately and return
// nothing, so they stay out of the success type.

@Controller()
export class TasksController {
  @Autowired() private readonly tasksService!: TasksService

  @Get('/')
  @ApiQueryParams(TASKS_QUERY_CONFIG)
  async list(ctx: Ctx<KickRoutes.TasksController['list']>) {
    return ctx.paginate((parsed) => this.tasksService.findPaginated(parsed), TASKS_QUERY_CONFIG)
  }

  @Get('/:id')
  async getById(ctx: Ctx<KickRoutes.TasksController['getById']>) {
    const result = await this.tasksService.findById(ctx.params.id)
    if (!result) {
      // Sends RFC 9457 problem+json now; returning nothing keeps the 404 out
      // of this route's inferred response type.
      ctx.problem.notFound({ detail: `Tasks ${ctx.params.id} not found` })
      return
    }
    return result
  }

  @Post('/', { body: createTasksSchema, name: 'CreateTasks' })
  async create(ctx: Ctx<KickRoutes.TasksController['create']>) {
    return reply.created(await this.tasksService.create(ctx.body))
  }

  @Put('/:id', { body: updateTasksSchema, name: 'UpdateTasks' })
  async update(ctx: Ctx<KickRoutes.TasksController['update']>) {
    return this.tasksService.update(ctx.params.id, ctx.body)
  }

  @Delete('/:id')
  async remove(ctx: Ctx<KickRoutes.TasksController['remove']>) {
    await this.tasksService.delete(ctx.params.id)
    return reply.noContent()
  }
}
