import { Controller, Get, Autowired, type Ctx } from '@forinda/kickjs'
import { HelloService } from './hello.service'

// `Ctx<KickRoutes.HelloController['<method>']>` is generated by
// `kick typegen` (auto-run on `kick dev`). The first run after a fresh
// scaffold creates `.kickjs/types/routes.ts` so this file typechecks.
// See https://kickjs.app/guide/typegen.

@Controller()
export class HelloController {
  @Autowired() private readonly helloService!: HelloService

  // Return-value handlers: the runtime sends the returned payload as
  // 200 json, and `kick typegen` infers the response type into
  // `KickRoutes.Api` — which is what makes the typed client
  // (@forinda/kickjs-client) end-to-end type-safe.
  @Get('/')
  index(_ctx: Ctx<KickRoutes.HelloController['index']>) {
    return this.helloService.greet('World')
  }

  @Get('/health')
  health(_ctx: Ctx<KickRoutes.HelloController['health']>) {
    return this.helloService.healthCheck()
  }
}
